title: Todd Mazierski
baseurl: ""
url: "https://toddmazierski.com"
github_username: toddmazierski
linkedin_username: toddmazierski
mastodon:
    - instance: mastodon.radio
      username: KE2AEQ
rss: RSS
google_site_verification: B5jhZxMLKyQGdUpUIhQ5HApOMBTWwynrVp7T0D5nxuY

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

assets_url: https://s3.amazonaws.com/assets.toddmazierski.com
