title: Todd Mazierski
baseurl: ""
url: "https://toddmazierski.com"
github_username: toddmazierski
linkedin_username: toddmazierski
rss: RSS

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

assets_url: https://s3.amazonaws.com/assets.toddmazierski.com
